---
- name: openjpeg-tools symlinks
  file:
    src: "/usr/bin/{{item.cmd}}"
    dest: "/usr/local/bin/{{item.link}}"
    state: link
  with_items:
    - { link: 'opj_decompress', cmd: 'opj2_decompress'}
    - { link: 'opj_dump', cmd: 'opj2_dump'}
    - { link: 'opj_compress', cmd: 'opj2_compress'}
