---
- name: install epel-release
  yum:
    name: epel-release
    state: present
- name: install required packages
  yum:
    pkg: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-2.7.1-3.el7.x86_64.rpm
    - https://kojipkgs.fedoraproject.org//packages/http-parser/2.7.1/3.el7/x86_64/http-parser-devel-2.7.1-3.el7.x86_64.rpm
    - '@xfce-desktop-environment'
    - autoconf
    - automake
    - bison
    - bzip2
    - curl
    - gcc-c++
    - git-core
    - glibc-headers
    - glibc-devel
    - htop
    - htop
    - httpd
    - httpd-devel
    - ImageMagick
    - java-1.8.0-openjdk
    - kernel-devel
    - kernel-headers
    - libcurl-devel
    - libffi-devel
    - libtiff
    - libtiff-tools
    - libtool
    - libxml2-devel
    - libxslt-devel
    - libyaml-devel
    - make
    - nano
    - nodejs
    - openjpeg
    - openjpeg2-tools
    - openssl-devel
    - patch
    - readline
    - readline-devel
    - sqlite
    - sqlite-devel
    - tree
    - vim
    - unzip
    - zlib
    - zlib-devel
